/* 
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
/**
 * Author:  admin
 * Created: 20-nov-2017

username: matteo
password: matteo
 */

CREATE TABLE utenti (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nome VARCHAR(32),
    cognome VARCHAR(32),
    dataNascita VARCHAR(10),
    motto VARCHAR(500),
    password VARCHAR(32) NOT NULL,
    urlImgProfilo VARCHAR(32),
    email VARCHAR(32) UNIQUE NOT NULL
    tipoUtente INTEGER NOT NULL,
    FOREIGN KEY (tipoUtente) REFERENCES tipiUtente(id)
);

CREATE TABLE tipiUtente (
    id  INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nomeTipo VARCHAR(5) UNIQUE NOT NULL
);

CREATE TABLE amici (
    idUtente1 INTEGER,
    idUtente2 INTEGER,
    PRIMARY KEY (idUtente1, idUtente2),
    FOREIGN KEY (idUtente1) REFERENCES utenti(id),
    FOREIGN KEY (idUtente2) REFERENCES utenti(id)
);

CREATE TABLE gruppi(
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nome VARCHAR(32)NOT NULL UNIQUE
);

CREATE TABLE iscrizioniGruppi (
    idUtente INTEGER,
    idGruppo INTEGER,
    PRIMARY KEY (idUtente, idGruppo),
    FOREIGN KEY (idUtente) REFERENCES utenti(id),
    FOREIGN KEY (idGruppo) REFERENCES gruppi(id)
);


CREATE TABLE post(
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    autorePost INTEGER,
    tipoDestinazione INTEGER,
    idUtenteDest INTEGER,
    idGruppoDest INTEGER,
    contenuto VARCHAR(500),
    linkAllegato VARCHAR(500),
    FOREIGN KEY (autorePost) REFERENCES utenti(id),
    FOREIGN KEY (idUtenteDest) REFERENCES utenti(id),
    FOREIGN KEY (idGruppoDest) REFERENCES gruppi(id)
);

INSERT INTO utenti ( id, nome, cognome, dataNascita, motto, password, urlImgProfilo, email, tipoUtente)
VALUES ( default, 'nome1', 'cognome1', '01-01-2001', 'motto1',
        'password1', 'url1', 'email1',1);

INSERT INTO utenti ( id, nome, cognome, dataNascita, motto, password, urlImgProfilo, email, tipoUtente)
VALUES ( default, 'nome2', 'cognome2', '02-02-2002', 'motto2',
        'password2', 'url2', 'email2',2);

INSERT INTO utenti ( id, nome, cognome, dataNascita, motto, password, urlImgProfilo, email, tipoUtente)
VALUES ( default, 'nome3', 'cognome3', '03-03-2003', 'motto3',
        'password3', 'url3', 'email3',2);

INSERT INTO utenti ( id, nome, cognome, dataNascita, motto, password, urlImgProfilo, email, tipoUtente)
VALUES ( default, 'nome0', 'cognome0', '00-00-2000', 'motto0',
        'password0', 'url0', 'email0',2);

INSERT INTO gruppi ( id, nome)
VALUES ( default, 'Molgonfieristi');

INSERT INTO gruppi ( id, nome)
VALUES ( default, 'Ritardatari');

INSERT INTO iscrizioniGruppi ( idUtente, idGruppo)
VALUES ( 1, 1);

INSERT INTO iscrizioniGruppi ( idUtente, idGruppo)
VALUES ( 2, 1);

INSERT INTO iscrizioniGruppi ( idUtente, idGruppo)
VALUES ( 3, 2);

INSERT INTO iscrizioniGruppi ( idUtente, idGruppo)
VALUES ( 4, 2);

INSERT INTO posts ( id, autorePost, tipoDestinazione, idUtenteDest, idGruppoDest, contenuto, tipoPost, linkAllegato)
VALUES ( default, 1, 1, 1, null, 'post1, sono un testo sulla bacheca di utente1', 1, null); 

INSERT INTO posts ( id, autorePost, tipoDestinazione, idUtenteDest, idGruppoDest, contenuto, tipoPost, linkAllegato)
VALUES ( default, 2, 1, 1, null, 'post2, sono un link sulla bacheca di utente2', 3, 'www.google.com'); 

INSERT INTO posts ( id, autorePost, tipoDestinazione, idUtenteDest, idGruppoDest, contenuto, tipoPost, linkAllegato)
VALUES ( default, 1, 2, 1, null, 'post3, sono un test sulla bacheca del gruppo mongolfieristi.', 1, null); 

